name: master-actions
on:
  push:
    branches: [push, pull_request]

jobs:
  linting-and-test:
    name: Lint and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: GolangCI Lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.26
          working-directory: .

      - name: Run tests & Upload coverage to Codacy
        run: |
          go get github.com/kyoh86/richgo
          go get github.com/schrej/godacov
          RICHGO_FORCE_COLOR=1 richgo test ./... -v -p=1 -count=1 -cover -coverprofile=coverage.out
          godacov -t ${{ secrets.CODACY_PROJECT_TOKEN }} -r ./coverage.out -c ${{ github.sha }}
      